### ISSUE TITLE
AWS Lambda and Puppeteer

### ISSUE THREAD

**Issue by sgiulians** [sean-hill/aws-puppeteer-lambda#1]
Hey hello Sean,
This is not an issue. I was wondering how you could have puppeteer installed within your node_modules folder and uploaded in AWS-Lambda. The whole package is huge (>>50Mb)
Did you manage to find a solution for that?

Simo

**Comment by kemelcodes** [comment]
@sgiulians  you have to upload the zip folder to AWS S3 bucket and copy the directory link. Then go to your AWS Lambda function page and in the section where you'd upload the code select "Upload a file from S3" then paste the link you copied in the field below.

**Comment by sgiulians** [comment]
cheers
